spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/judge.db
    username:
    password:


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #???????package?????????
  typeAliasesPackage: com.dong.djudge.entity
  global-config:
    #???????
    db-config:
      #????
      id-type: ASSIGN_ID
    banner: false
  #????
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
